# Generated by Django 5.0.4 on 2024-05-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verevapp', '0002_alter_product_category_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_user'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('JAWA', 'JAWA'), ('SULAWESI', 'SULAWESI'), ('PAPUA', 'PAPUA'), ('KALIMANTAN', 'KALIMANTAN'), ('SUMATERA', 'SUMATERA')], max_length=100),
        ),
    ]
