# Generated by Django 5.0.4 on 2024-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verevapp', '0003_customer_profile_image_alter_customer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('PAPUA', 'PAPUA'), ('SUMATERA', 'SUMATERA'), ('KALIMANTAN', 'KALIMANTAN'), ('JAWA', 'JAWA'), ('SULAWESI', 'SULAWESI')], max_length=100),
        ),
    ]
